"""First-run auto-configuration for MyAIOne Inference.

Invoked from ``myai --onboarding`` and (optionally) from any code path
that lands on an unconfigured install: if we detect a usable
``myaidev-method`` session or a manual ``MYAIONE_API_KEY`` env var, we
provision a key (when needed), pick a model, and write a minimal
``config.yaml`` so the TUI drops straight into a working session.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

from myai_cli.providers.myaione import (
    MYAIONE_API_KEY_ENV,
    MyaidevAuth,
    MyaidevAuthError,
    ModelInfo,
    bucket_models,
    list_chat_models,
    myaione_base_url,
    provision_inference_key,
    read_myaidev_auth,
    write_api_key_to_env,
)


# ─── User-visible printing ───────────────────────────────────────────────────


def _print_header() -> None:
    print()
    print("━━━ MyAIOne Inference · auto-configuration ━━━")
    print()


def _print_info(msg: str) -> None:
    print(f"  → {msg}")


def _print_success(msg: str) -> None:
    print(f"  \u2713 {msg}")


def _print_warn(msg: str) -> None:
    print(f"  \u26a0 {msg}")


def _print_error(msg: str) -> None:
    print(f"  \u2717 {msg}", file=sys.stderr)


# ─── Model picker ────────────────────────────────────────────────────────────


def _prompt_model_choice(local: list[ModelInfo], proxied: list[ModelInfo]) -> Optional[ModelInfo]:
    """Prompt the user to pick a chat model, defaulting to the first local one.

    Returns ``None`` if there are no chat-capable models at all, or if the
    user aborts via Ctrl+D (EOF).
    """
    ordered: list[ModelInfo] = [*local, *proxied]
    if not ordered:
        return None

    print()
    print("  Available chat models:")
    if local:
        print(f"    Local (served by MyAIOne's own compute):")
        for i, m in enumerate(local, start=1):
            marker = " (default)" if i == 1 else ""
            print(f"      {i}. {m.id}{marker}")
    if proxied:
        offset = len(local)
        if local:
            print(f"    Proxied (routed through MyAIOne to an external provider):")
        else:
            print(f"    Proxied:")
        for i, m in enumerate(proxied, start=offset + 1):
            print(f"      {i}. {m.id}  [{m.owned_by}]")

    default_idx = 1
    try:
        raw = input(f"\n  Pick a model [1-{len(ordered)}, Enter = {ordered[0].id}]: ").strip()
    except EOFError:
        return None
    if not raw:
        return ordered[default_idx - 1]
    try:
        choice = int(raw)
    except ValueError:
        _print_warn(f"'{raw}' isn't a number — using default {ordered[0].id}")
        return ordered[0]
    if choice < 1 or choice > len(ordered):
        _print_warn(f"out of range — using default {ordered[0].id}")
        return ordered[0]
    return ordered[choice - 1]


# ─── Config writer ───────────────────────────────────────────────────────────


def _write_default_config(model_id: str) -> Path:
    """Populate config.yaml with MyAIOne Inference as the default provider.

    Merges into any existing config (so users who already customised their
    config don't get it stomped).  If no config exists, seeds a minimal one.
    """
    import yaml

    from hermes_constants import get_config_path

    config_path = get_config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)

    data: dict = {}
    if config_path.exists():
        try:
            loaded = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
            if isinstance(loaded, dict):
                data = loaded
        except yaml.YAMLError:
            # Malformed existing config — leave it alone; the caller will
            # surface the warning and the user can fix it manually.
            pass

    model_section = data.get("model")
    if not isinstance(model_section, dict):
        model_section = {}
    model_section.update(
        {
            "provider": "myaione",
            "id": model_id,
            "base_url": myaione_base_url(),
        }
    )
    data["model"] = model_section

    config_path.write_text(
        "# Auto-generated by `myai --onboarding` (MyAIOne Inference default).\n"
        "# Edit freely; re-running onboarding only touches the `model:` section.\n"
        + yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    return config_path


# ─── Top-level entry points ──────────────────────────────────────────────────


def _resolve_or_provision_api_key(auth: Optional[MyaidevAuth]) -> Optional[str]:
    """Return an inference API key, provisioning via the website if possible.

    Order:
      1. ``MYAIONE_API_KEY`` env var — user already has a key (hand-pasted
         or cached from a previous run).  Use it as-is.
      2. ``auth`` present → try exchanging the session token via
         ``dev.myai1.ai/api/user/api-keys``.  Returns None if the website
         hasn't shipped bearer auth yet — caller surfaces guidance.
      3. Neither → return None so the caller prompts the user to log in.
    """
    env_key = os.environ.get(MYAIONE_API_KEY_ENV, "").strip()
    if env_key:
        _print_info(f"using existing {MYAIONE_API_KEY_ENV} from env")
        return env_key

    if auth is None:
        return None

    _print_info(f"provisioning inference key via dev.myai1.ai as {auth.user_email or auth.user_id}")
    try:
        key = provision_inference_key(auth.token)
    except RuntimeError as exc:
        _print_error(str(exc))
        return None
    if not key:
        _print_warn(
            "the dev.myai1.ai bearer endpoint isn't available yet. Create a key at "
            "https://dev.myai1.ai and paste it into MYAIONE_API_KEY."
        )
        return None
    return key


def run_onboarding(*, force_prompt: bool = False) -> int:
    """Run the MyAIOne Inference onboarding flow.

    Returns an exit-code-style int: ``0`` on success (config written and
    model picked), non-zero on failure.  When ``force_prompt`` is False
    and nothing needs doing (config already points at myaione and the
    key works), we return 0 without prompting.
    """
    _print_header()

    # 1. Read myaidev-method auth (may be absent — that's fine)
    try:
        auth = read_myaidev_auth()
    except MyaidevAuthError as exc:
        _print_error(f"{exc}")
        return 2

    if auth:
        _print_info(f"detected myaidev-method login ({auth.user_email or auth.user_id})")
    else:
        if not os.environ.get(MYAIONE_API_KEY_ENV, "").strip():
            _print_warn(
                "no myaidev-method login and no MYAIONE_API_KEY — run `myaidev-method login` "
                "or set MYAIONE_API_KEY in ~/.myai/.env, then re-run `myai --onboarding`."
            )
            return 3

    # 2. Get an inference API key (env → provision → fail)
    api_key = _resolve_or_provision_api_key(auth)
    if not api_key:
        return 4

    # 3. Fetch models, bucket them, prompt the user
    try:
        models = list_chat_models(api_key)
    except RuntimeError as exc:
        _print_error(
            f"could not list models at {myaione_base_url()}/models: {exc}. "
            "Your key may be invalid — try `myaidev-method login` or regenerate at https://dev.myai1.ai."
        )
        return 5
    if not models:
        _print_error("the server returned no chat-capable models — nothing to pick")
        return 6

    local, proxied = bucket_models(models)
    picked = _prompt_model_choice(local, proxied)
    if picked is None:
        _print_error("no model selected — aborting")
        return 7

    # 4. Write .env and config.yaml
    env_path = write_api_key_to_env(api_key)
    _print_success(f"wrote {MYAIONE_API_KEY_ENV} to {env_path}")
    config_path = _write_default_config(picked.id)
    _print_success(f"set default model → {picked.id} in {config_path}")

    # Put the key in-process too so the TUI launches without a fresh env load.
    os.environ[MYAIONE_API_KEY_ENV] = api_key

    print()
    _print_success(f"ready — launching TUI with MyAIOne Inference ({picked.id})")
    print()
    return 0
